CREATE TABLE IF NOT EXISTS footer (
  id SERIAL PRIMARY KEY, data JSONB NOT NULL,
  inserted_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW()
);
ALTER TABLE footer ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON footer FOR SELECT USING (true);
