"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SITE_URL = void 0;
/**
 * GENERATED by tools/generate-site-url.mjs — do not edit by hand.
 *
 * Regenerated on every build from the deployment environment. See
 * tools/site-origin.mjs for how the value is chosen.
 */
exports.SITE_URL = 'https://rabinr.in';
//# sourceMappingURL=site-url.js.map