/**
 * GENERATED by tools/generate-site-url.mjs — do not edit by hand.
 *
 * Regenerated on every build from the deployment environment. See
 * tools/site-origin.mjs for how the value is chosen.
 */
export const SITE_URL = 'https://www.rabinr.in';
