mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    createdAt_expr: "request.time",
    id_expr: "uuidV4()"
  })
}

query GetProjects @auth(level: USER) {
  projects(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    title
    description
  }
}

mutation UpdateProject($id: UUID!, $description: String) @auth(level: USER) {
  project_update(key: {id: $id}, data: {description: $description})
}

query ListSkills @auth(level: PUBLIC, insecureReason: "Skills are safe to expose to the public") {
  skills {
    id
    name
    skillCategory
  }
}