import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import type { PortfolioMedia } from '../../../../../core/models/portfolio.models';

/**
 * Sticky visual companion to the process timeline. Shows the AI-generated
 * illustration for whichever process step is currently active — one distinct
 * visual per stage, so the panel changes as the visitor scrolls the timeline
 * rather than showing a single reused image.
 */
@Component({
  selector: 'app-process-visual',
  templateUrl: './process-visual.html',
  styleUrl: './process-visual.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'pv', '[attr.aria-hidden]': 'true' },
})
export class ProcessVisual {
  /** Zero-based index of the currently active process step (0–6). */
  readonly activeStep = input(0);

  protected readonly media = computed(() => VISUAL_KEYS[this.activeStep()] ?? VISUAL_KEYS[0]);
}

/** The source PNGs in `public/media/process` are all 1672 × 941, shipped with
 *  WebP variants at 640 / 960 / 1366 generated by `tools/optimize-screenshots.mjs`. */
const PROCESS_WIDTHS = [640, 960, 1366] as const;

export const VISUAL_KEYS = [
  { key: 'discover', media: shot('discover') },
  { key: 'define', media: shot('define') },
  { key: 'design', media: shot('design') },
  { key: 'build', media: shot('build') },
  { key: 'test', media: shot('test') },
  { key: 'launch', media: shot('launch') },
  { key: 'evolve', media: shot('evolve') },
] as const;

export type VisualKey = (typeof VISUAL_KEYS)[number]['key'];

function shot(name: string): PortfolioMedia {
  return {
    kind: 'image',
    src: `/media/process/${name}.png`,
    sources: [
      {
        type: 'image/webp',
        srcset: PROCESS_WIDTHS.map((w) => `/media/process/${name}-${w}.webp ${w}w`).join(', '),
      },
    ],
    alt: '',
    width: 1672,
    height: 941,
  };
}