/**
 * Vercel pre-build script: injects environment variables into environment.prod.ts
 *
 * Required Vercel environment variables (set in Vercel dashboard):
 *   EMAILJS_SERVICE_ID      – EmailJS service ID
 *   EMAILJS_TEMPLATE_ID     – EmailJS template ID
 *   EMAILJS_PUBLIC_KEY      – EmailJS public key
 *   EMAILJS_RECIPIENT_EMAIL – Email address to receive messages
 */

const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

const serviceId      = process.env['EMAILJS_SERVICE_ID']      || 'service_your_service_id';
const templateId     = process.env['EMAILJS_TEMPLATE_ID']     || 'template_your_template_id';
const publicKey      = process.env['EMAILJS_PUBLIC_KEY']      || 'your_public_key';
const recipientEmail = process.env['EMAILJS_RECIPIENT_EMAIL'] || 'your-email@example.com';

const content = `// Auto-generated by scripts/set-env.js during Vercel build — do not edit manually.
export const environment = {
  production: true,
  emailjs: {
    serviceId: '${serviceId}',
    templateId: '${templateId}',
    publicKey: '${publicKey}',
    recipientEmail: '${recipientEmail}'
  }
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
console.log('set-env: environment.prod.ts written ✓');
