/**
 * Generates server/src/shared/content/portfolio.content.ts from the single
 * authored client config (src/app/core/config/*). Run via `npm run prebuild`
 * or `npm run predev` inside server/ so the Express content route and the
 * client can never disagree about what the site says. Do not edit the
 * generated file by hand.
 *
 * This runs under tsx (the client config is TypeScript), and tsx is a server
 * devDependency, so no extra tooling is required.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PRICING_PLANS } from '../../src/app/core/config/hire.content.ts';
import {
  ABOUT,
  AVAILABILITY,
  CONTACT,
  EXPERIENCE,
  HERO,
  PROCESS,
  PROFILE,
  PROJECTS,
  SECTIONS,
  SERVICES,
  SITE_MEDIA,
  SITE_SETTINGS,
  SKILLS,
  TESTIMONIALS,
  UI_COPY,
} from '../../src/app/core/config/portfolio.content.ts';

const CONTENT = {
  profile: PROFILE,
  projects: PROJECTS,
  services: SERVICES,
  experience: EXPERIENCE,
  skills: SKILLS,
  process: PROCESS,
  testimonials: TESTIMONIALS,
  media: SITE_MEDIA,
  hero: HERO,
  about: ABOUT,
  availability: AVAILABILITY,
  contact: CONTACT,
  siteSettings: SITE_SETTINGS,
  sections: SECTIONS,
  uiCopy: UI_COPY,
  pricingPlans: PRICING_PLANS,
};

const outPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../src/shared/content/portfolio.content.ts',
);

const banner = `/**
 * GENERATED by server/scripts/generate-content.ts \u2014 do not edit by hand.
 *
 * Regenerated via \`npm run prebuild\` / \`npm run predev\` inside server/ from
 * the single authored client config (src/app/core/config). The shape mirrors
 * api/content.ts so the dev Express route and the production Vercel function
 * return identical bundles.
 */

`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + `export const CONTENT = ${JSON.stringify(CONTENT, null, 2)};\n`, 'utf8');
console.log(`[generate-content] wrote ${outPath}`);
