type User @table {
  firstName: String!
  lastName: String!
  email: String!
  createdAt: Timestamp!
  bio: String
  phone: String
  linkedInUrl: String
  gitHubUrl: String
  websiteUrl: String
  profilePictureUrl: String
}

type Project @table {
  user: User
  title: String!
  description: String!
  projectType: String!
  createdAt: Timestamp!
  demoUrl: String
  repositoryUrl: String
  featured: Boolean
  technologiesUsed: [String]
}

type ProjectImage @table {
  project: Project
  imageUrl: String!
  createdAt: Timestamp!
  caption: String
  order: Int
}

type Skill @table {
  user: User
  name: String!
  skillCategory: String!
  createdAt: Timestamp!
  proficiencyLevel: String
}

type Education @table {
  user: User
  institution: String!
  degree: String!
  startDate: Date!
  createdAt: Timestamp!
  endDate: Date
  description: String
}

type Experience @table {
  user: User
  company: String!
  role: String!
  startDate: Date!
  createdAt: Timestamp!
  endDate: Date
  responsibilities: String
}